name: Playwright Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # --- Run tests in shards ---
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shardIndex: [1, 2, 3]   # split into 3 shards (adjust as needed)
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (shard ${{ matrix.shardIndex }})
        run: npx playwright test --shard=${{ matrix.shardIndex }}/3 --reporter=line,allure-playwright

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.shardIndex }}
          path: allure-results

  # --- Merge results and generate report ---
  merge-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Download Allure results from all shards
        uses: actions/download-artifact@v3
        with:
          path: ./allure-artifacts

      - name: Merge Allure results
        run: |
          mkdir merged-results
          cp -r allure-artifacts/*/* merged-results/ || true

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: npx allure generate merged-results --clean -o allure-report

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 7