name: Playwright Tests with Allure

on:
  workflow_dispatch:
    inputs:
      spec:
        description: "Path to spec/test file to run (e.g. tests/example.spec.js). Leave empty to run all tests"
        required: false
        default: ""

jobs:
  # --- Run tests in shards across all browsers ---
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, "Google Chrome"]
        shardIndex: [1, 2, 3]   # 3 shards
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Get Playwright projects
        id: set-projects
        run: |
          projects=$(node -e "
            import(path.resolve('./playwright.config.js'))
              .then(cfg => console.log(JSON.stringify(cfg.default.projects.map(p => p.name))))
          " --input-type=module)
          echo "projects=$projects" >> $GITHUB_OUTPUT

      - name: Run Playwright tests (shard ${{ matrix.shardIndex }} on ${{ matrix.browser }})
        run: |
          if [ -z "${{ github.event.inputs.spec }}" ]; then
            npx playwright test --shard=${{ matrix.shardIndex }}/3 --project=${{ matrix.browser }} --reporter=line,allure-playwright
          else
            npx playwright test ${{ github.event.inputs.spec }} --shard=${{ matrix.shardIndex }}/3 --project=${{ matrix.browser }} --reporter=line,allure-playwright
          fi

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}-${{ matrix.shardIndex }}
          path: allure-results

  # --- Merge results and generate report ---
  merge-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Download Allure results from all shards & browsers
        uses: actions/download-artifact@v4
        with:
          path: ./allure-artifacts

      - name: Merge Allure results
        run: |
          mkdir merged-results
          cp -r allure-artifacts/*/* merged-results/ || true

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: npx allure generate merged-results --clean -o allure-report

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 7
